version: 2.0.{build}
environment:
  NUGET_SOURCE: https://www.myget.org/F/splat/api/v2/package
  NUGET_APIKEY:
    secure: PWu3pIoHDora6ry50WZh34jN1uvbTovWkZ73QUxWunMpx5ZsbrkOuiKwDtRMHtHg
build_script:
- ps: >-
    ./bootstrap.ps1

    ./build.cmd
artifacts:
- path: artifacts/*
- path: '**/bin/*'