version: 1.0.{build}
environment:
  NUGET_SOURCE: https://www.myget.org/F/splat/api/v2/package
#  NUGET_APIKEY:
#    secure: [some token here]
build_script:
- ps: >-
    ./bootstrap.ps1

    ./build.cmd
artifacts:
- path: artifacts/*
- path: '**/bin/*'