trigger:
- master
- rel/*

pr:
- master
- rel/*

pool:
  vmImage: vs2017-win2016

steps:
- task: BatchScript@1
  inputs:
    filename: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
    arguments: -no_logo
    modifyEnvironment: true
  displayName: Setup Environment Variables

- script: build.cmd
  displayName: Build 
  env:
    SIGNCLIENT_SECRET: $(SignClientSecret)
    SIGNCLIENT_USER: $(SignClientUser)
    COVERALLS_TOKEN: $(COVERALLS_TOKEN)
    ArtifactDirectory: $(System.DefaultWorkingDirectory)\Artifacts

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit
    testResultsFiles: '**/testresults-*.trx' 
    searchFolder: $(System.DefaultWorkingDirectory)\Artifacts\tests' # Optional
    #mergeTestResults: false # Optional
    #testRunTitle: # Optional
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    #publishRunAttachments: true # Optional    
- task: CopyFiles@2
  inputs:
    Contents: 'artifacts/packages/*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)\packages'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
  inputs:
    pathToPublish: '$(build.artifactstagingdirectory)\packages'
    artifactType: container
    artifactName: Packages

- task: CopyFiles@2
  inputs:
    Contents: 'artifacts/binaries/**/*'
    TargetFolder: '$(build.artifactstagingdirectory)\binaries'

- task: PublishBuildArtifacts@1
  displayName: Publish Binaries
  inputs:
    pathToPublish: '$(build.artifactstagingdirectory)\binaries'
    artifactType: container
    artifactName: Binaries
