trigger:
- master
- rel/*
- preview/*

pr:
- master
- rel/*
- preview/*

resources:
  repositories:
    - repository: templates
      type: github
      name: ReactiveUI/ReactiveUI.Cake.Recipe

jobs:
- template: Azure/azure-pipelines.yaml@templates  # Template reference